title = "Quadric"

[ellipsoid]
name = "Ellipsoid"
thumbnail = "textures/thumbs/quadric/ellipsoid.png"
bounds_radius = 1.7
isosurface_raymarch_steps = 100
scale = 1.3
dvr_falloff = 2.0
max_abs_curvature_falloff = 0.4
normal_length_falloff = 0.1
parameters = [{name = "a", value = 1.5},
              {name = "b", value = 1},
              {name = "c", value = 0.75}]
expression = "x^2/a^2+y^2/b^2+z^2/c^2-1"

[elliptic_cone]
name = "Elliptic Cone"
thumbnail = "textures/thumbs/quadric/elliptic_cone.png"
bounds_shape = "box"
bounds_radius = 1.5
isosurface_raymarch_steps = 100
scale = 1.0
dvr_falloff = 2.0
gaussian_curvature_falloff = 0.1
mean_curvature_falloff = 1.0
max_abs_curvature_falloff = 0.2
normal_length_falloff = 0.3
parameters = [{name = "a", value = 1},
              {name = "b", value = 1},
              {name = "c", value = 1}]
expression = "x^2/a^2+y^2/b^2-z^2/c^2"

[elliptic_cylinder]
name = "Elliptic Cylinder"
thumbnail = "textures/thumbs/quadric/elliptic_cylinder.png"
bounds_shape = "box"
bounds_radius = 2.0
isosurface_raymarch_steps = 100
scale = 0.9
dvr_falloff = 2.0
normal_length_falloff = 0.5
parameters = [{name = "a", value = 1},
              {name = "b", value = 1}]
expression = "x^2/a^2+y^2/b^2-1"

[elliptic_paraboloid]
name = "Elliptic Paraboloid"
thumbnail = "textures/thumbs/quadric/elliptic_paraboloid.png"
bounds_shape = "box"
bounds_radius = 3.0
isosurface_raymarch_steps = 100
scale = 0.7
dvr_falloff = 2.0
max_abs_curvature_falloff = 0.5
normal_length_falloff = 0.3
parameters = [{name = "a", value = 1},
              {name = "b", value = 1}]
expression = "x^2/a^2+y^2/b^2-z"

[hyperbolic_cylinder]
name = "Hyperbolic Cylinder"
thumbnail = "textures/thumbs/quadric/hyperbolic_cylinder.png"
bounds_shape = "box"
bounds_radius = 2.0
isosurface_raymarch_steps = 100
scale = 0.7
dvr_falloff = 1.0
max_abs_curvature_falloff = 0.6
normal_length_falloff = 0.06
parameters = [{name = "a", value = 0.5},
              {name = "b", value = 0.5}]
expression = "x^2/a^2-y^2/b^2+1"

[hyperbolic_paraboloid]
name = "Hyperbolic Paraboloid"
thumbnail = "textures/thumbs/quadric/hyperbolic_paraboloid.png"
bounds_radius = 3.0
isosurface_raymarch_steps = 100
scale = 0.7
dvr_falloff = 1.0
gaussian_curvature_falloff = 0.25
mean_curvature_falloff = 2.0
max_abs_curvature_falloff = 0.75
normal_length_falloff = 0.25
parameters = [{name = "a", value = 1},
              {name = "b", value = 1}]
expression = "x^2/a^2-y^2/b^2-z"

[parabolic_cylinder]
name = "Parabolic Cylinder"
thumbnail = "textures/thumbs/quadric/parabolic_cylinder.png"
bounds_shape = "box"
bounds_radius = 2.0
isosurface_raymarch_steps = 100
scale = 0.8
dvr_falloff = 2.0
max_abs_curvature_falloff = 1.25
normal_length_falloff = 0.3
parameters = [{name = "r", value = 1}]
expression = "x^2+2*r*z"
