title = "Quintic"

[chmutov_quintic]
name = "Chmutov Quintic"
thumbnail = "textures/thumbs/quintic/chmutov_quintic.png"
bounds_shape = "box"
bounds_radius = 1.1
isosurface_raymarch_steps = 100
scale = 1.3
dvr_raymarch_steps = 300
dvr_falloff = 0.75
gaussian_curvature_falloff = 0.075
mean_curvature_falloff = 0.15
max_abs_curvature_falloff = 0.05
normal_length_falloff = 0.025
code_global = '''
float T_5(float x) {
  float x2=x*x;
  float x4=x2*x2;
  return x*(16.*x4-20.*x2+5.);
}
'''
comment = '''
\mathrm{where}\; T_5(x)=16x^5-20x^3+5x+1\\
&\mathrm{is\;the\;Chebyshev\;polynomial\;of\;the\;first\;kind\;of\;degree\;5.}
'''
expression = "T_5(x)+T_5(y)+T_5(z)+1"

[kiss]
name = "Kiss"
thumbnail = "textures/thumbs/quintic/kiss.png"
bounds_radius = 1.2
isosurface_raymarch_steps = 110
scale = 1.7
dvr_falloff = 7.0
gaussian_curvature_falloff = 0.15
mean_curvature_falloff = 0.15
max_abs_curvature_falloff = 0.035
normal_length_falloff = 0.45
expression = "x^2+y^2-(1-z)*z^4"

[labs_15-cusp_quintic]
name = "Labs 15-Cusp Quintic"
thumbnail = "textures/thumbs/quintic/labs_15-cusp_quintic.png"
bounds_radius = 4.0
isosurface_raymarch_steps = 400
scale = 0.55
dvr_raymarch_steps = 300
dvr_falloff = 0.1
gaussian_curvature_falloff = 0.75
mean_curvature_falloff = 0.25
max_abs_curvature_falloff = 0.15
normal_length_falloff = 0.0025
code_global = '''
float S_5(float x, float y) {
  vec2 xy=vec2(x,y);
  vec2 xy2=xy*xy;
  vec2 xy3=xy2*xy;
  vec2 xy4=xy2*xy2;
  vec2 xy5=xy2*xy3;
  return xy5.x+xy2.y*(-10.*xy3.x+5.*x*xy2.y-10.*xy2.x-5.*xy2.y+20.)-5.*xy4.x
         +20.*xy2.x-16.;
}
float t(float z) {
  float z2=z*z;
  float z3=z2*z;
  float z5=z3*z2;
  return -3.*z5+10.*z3-15.*z-8.;
}
'''
comment = '''
\mathrm{where}\\
&\begin{aligned}S_5(x,y)=\;&x^5-10x^3y^2+5xy^4-5x^4-10x^2y^2&\\
&-5y^4+20x^2+20y^2-16,\end{aligned}\\
&t(z)=-3z^5+10z^3-15z-8.
'''
expression = "S_5(x,y)+t(z)"

[peninsula]
name = "Peninsula"
thumbnail = "textures/thumbs/quintic/peninsula.png"
bounds_shape = "box"
bounds_radius = 2.0
isosurface_raymarch_steps = 120
scale = 0.8
dvr_raymarch_steps = 250
dvr_falloff = 1.5
gaussian_curvature_falloff = 0.75
mean_curvature_falloff = 1.0
max_abs_curvature_falloff = 0.55
normal_length_falloff = 0.05
expression = "x^2+y^3+z^5-1"

[togliatti]
name = "Togliatti"
thumbnail = "textures/thumbs/quintic/togliatti.png"
bounds_radius = 6
isosurface_raymarch_method = "fixed-step"
isosurface_raymarch_steps = 500
scale = 0.38
dvr_raymarch_steps = 200
dvr_falloff = 0.0001
gaussian_curvature_falloff = 1.0
mean_curvature_falloff = 0.35
max_abs_curvature_falloff = 0.2
normal_length_falloff = 0.0001
parameters = [{name = "a", value = 1.66250775111}]
expression = '''
64*(x-1)
*(x^4-4*x^3-10*x^2*y^2-4*x^2+16*x-20*x*y^2+5*y^4+16-20*y^2)
-5*a*(2*z-a)*[4*(x^2+y^2-z^2)+(1+3*sqrt(5))]^2'''