title = "Sextic"

[barth_sextic]
name = "Barth Sextic"
thumbnail = "textures/thumbs/sextic/barth_sextic.png"
bounds_radius = 3.0
isosurface_raymarch_steps = 200
scale = 0.7
dvr_raymarch_steps = 400
dvr_falloff = 0.45
gaussian_curvature_falloff = 0.25
mean_curvature_falloff = 0.1
max_abs_curvature_falloff = 0.05
normal_length_falloff = 0.005
parameters = [{name = "w", value = 1}]
code_global = "const float phi=1.618033988;"
comment = '''
\mathrm{where}\; \phi=\frac{1+\sqrt{5}}{2}\;\mathrm{\;is\;the\;golden\;ratio.}'''
expression = '''
4*(phi^2*x^2-y^2)*(phi^2*y^2-z^2)*(phi^2*z^2-x^2)
-(1+2*phi)*(x^2+y^2+z^2-w^2)^2*w^2'''

[chmutov_sextic]
name = "Chmutov Sextic"
thumbnail = "textures/thumbs/sextic/chmutov_sextic.png"
bounds_radius = 2.0
isosurface_raymarch_steps = 200
scale = 1.3
dvr_raymarch_steps = 300
dvr_falloff = 1.2
gaussian_curvature_falloff = 0.05
mean_curvature_falloff = 0.25
max_abs_curvature_falloff = 0.06
normal_length_falloff = 0.03
code_global = '''
float T_6(float x) {
  float x2=x*x;
  float a=3.-4.*x2;
  return 2.*x2*a*a-1.;
}
'''
comment = '''
\mathrm{where}\; T_6(x)=32x^6-48x^4+18x^2-1\\
&\mathrm{is\;the\;Chebyshev\;polynomial\;of\;the\;first\;kind\;of\;degree\;6.}'''
expression = "T_6(x)+T_6(y)+T_6(z)"

[heart]
name = "Heart"
thumbnail = "textures/thumbs/sextic/heart.png"
bounds_radius = 1.5
isosurface_raymarch_steps = 150
scale = 1.4
dvr_raymarch_steps = 300
dvr_falloff = 10.0
gaussian_curvature_falloff = 0.15
mean_curvature_falloff = 0.3
max_abs_curvature_falloff = 0.1
normal_length_falloff = 0.35
expression = "(x^2+9/4*y^2+z^2-1)^3-x^2*z^3-9/80*y^2*z^3"

[high_silhouette]
name = "High Silhouette"
thumbnail = "textures/thumbs/sextic/high_silhouette.png"
bounds_radius = 2.0
isosurface_raymarch_steps = 140
isosurface_raymarch_root_test = "taylor 1st-order"
isosurface_raymarch_gradient = "central difference"
scale = 1.0
dvr_raymarch_steps = 300
dvr_falloff = 20.0
gaussian_curvature_falloff = 1.0
mean_curvature_falloff = 0.75
max_abs_curvature_falloff = 0.5
normal_length_falloff = 0.1
expression = "x^6-y^5-2*x^3*y+y^2"

[hunt]
name = "Hunt"
thumbnail = "textures/thumbs/sextic/hunt.png"
bounds_radius = 4.0
isosurface_raymarch_steps = 700
scale = 0.55
dvr_raymarch_steps = 300
dvr_falloff = 0.001
gaussian_curvature_falloff = 1.0
mean_curvature_falloff = 0.25
max_abs_curvature_falloff = 0.25
normal_length_falloff = 0.0002
expression = "4*(x^2+y^2+z^2-13)^3+27*(3*x^2+y^2-4*z^2-12)^2"

[klein_bottle]
name = "Klein Bottle"
thumbnail = "textures/thumbs/sextic/klein_bottle.png"
bounds_radius = 4.1
isosurface_raymarch_steps = 350
isosurface_raymarch_root_test = "taylor 2nd-order"
scale = 0.5
dvr_raymarch_steps = 500
dvr_falloff = 0.25
gaussian_curvature_falloff = 0.5
mean_curvature_falloff = 1.0
max_abs_curvature_falloff = 0.4
normal_length_falloff = 0.0012
expression = '''
(x^2+y^2+z^2+2*y-1)*[(x^2+y^2+z^2-2*y-1)^2-8*z^2]
+16*x*z*(x^2+y^2+z^2-2*y-1)'''